/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm")
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://repo.eclipse.org/content/groups/releases/")
    }

}

dependencies {
    api(libs.com.github.mwiede.jsch)
    api(libs.commons.logging.commons.logging)
    api(libs.org.eclipse.swt.org.eclipse.swt.gtk.linux.x86.v64)
    implementation(kotlin("stdlib-jdk8"))
}

group = "org.programmerplanet"
version = "0.7"
description = "sshtunel-ng"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

kotlin {
    jvmToolchain(18)
}
